export * from "./route-path";
export * from "./api-path";
export * from "./phoneRegExr";
export * from "./roles";
export * from "./classroomRegExr";
export * from "./nameRegExr";
export * from "./idstudentRegExr";
export * from "./subjectRegExr";
export * from "./groupRegExr";
