export const ROUTE_PATH = {
  DASHBOARD: "/dashboard",
  STUDENT_LIST: "/student",
  CREATE_STUDENT: "/student/create",
  EDIT_STUDENT: "/student/edit",
  SUBJECT_LIST: "/subject",
  EDIT_SUBJECT: "/subject/edit",
  CREATE_SUBJECT: "/subject/create",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  CLASSROOM_LIST: "/classroom",
  CREATE_CLASSROOM: "/classroom/create",
  EDIT_CLASSROOM: "/classroom/edit",
  TEACHER_NOTIFY:"/teacher/notifi",
  STUDENT_SEND:"/student/send",
  TEACHER_SEND:"/teacher/send",
  REGISTER_GROUP:"/register/student",
  COMMENT:"/student/comment",
  TEACHER_LIST: "/teacher",
  EDIT_TEACHER: "/teacher/edit",
  CHANGEPASS: "/change-password",
  MANAGE_STUDENT: "/classroom/manage-student",
};
