export const ROUTE_PATH = {
  DASHBOARD: "/dashboard",
  STUDENT_LIST: "/student",
  CREATE_STUDENT: "/student/create",
  EDIT_STUDENT: "/student/edit",
  SUBJECT_LIST: "/subject",
  EDIT_SUBJECT: "/subject/edit",
  CREATE_SUBJECT: "/subject/create",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  CLASSROOM_LIST: "/classroom",
  CREATE_CLASSROOM: "/classroom/create",
  EDIT_CLASSROOM: "/classroom/edit",
  MANAGE_STUDENT: "/classroom/student",
  ADD_CLASSROOMSTUDENT: "/classroom/add-student",
  GROUP_LIST:"/classroom/group",
  CREATE_GROUP:"/classroom/group/create",
  ADD_GROUPSTUDENT:"/classroom/group/add-student",
  GROUP_CONDITION:"/classroom/edit-group-condition",
  TEACHER_LIST: "/teacher",
  EDIT_TEACHER: "/teacher/edit",
  CHANGEPASS: "/change-password",
};
