export const ROUTE_PATH = {
  DASHBOARD: "/dashboard",
  STUDENT_LIST: "/student",
  CREATE_STUDENT: "/student/create",
  EDIT_STUDENT: "/student/edit",
  SUBJECT_LIST: "/subject",
  EDIT_SUBJECT: "/subject/edit",
  CREATE_SUBJECT: "/subject/create",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  CLASSROOM_LIST: "/classroom",
  CREATE_CLASSROOM: "/classroom/create",
  EDIT_CLASSROOM: "/classroom/edit",
  MANAGE_CLASSROOM_STUDENT: "/classroom/student",
  EDIT_CLASSROOM_STUDENT: "/classroom/student/edit",
  ADD_CLASSROOMSTUDENT: "/classroom/add-student",
  GROUP_LIST: "/classroom/group",
  CREATE_GROUP: "/classroom/create-group",
  ADD_GROUPSTUDENT: "/classroom/group/add-student",
  GROUP_CONDITION: "/classroom/edit-group-condition",
  TEACHER_LIST: "/teacher",
  EDIT_TEACHER: "/teacher/edit",
  CHANGEPASS: "/change-password",
  EDIT_GROUP: "/classroom/group/edit",
  MANAGE_GROUP_STUDENT: "/classroom/group/student",
  EDIT_GROUP_STUDENT: "/classroom/group/student/edit",
  CREATE_TEACHER: "/teacher/create",
};
